const monitorReceive = [
    {status:"test1", wms_doc:"wms_doc1", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844.235, received_pallet:89545.55},
    {status:"test2", wms_doc:"wms_doc2", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844, received_pallet:89545},
    {status:"test3", wms_doc:"wms_doc3", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844, received_pallet:89545},
    {status:"test4", wms_doc:"wms_doc4", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844, received_pallet:89545},
    {status:"test5", wms_doc:"wms_doc5", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844, received_pallet:89545},
    {status:"test1", wms_doc:"wms_doc1", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844, received_pallet:89545},
    {status:"test2", wms_doc:"wms_doc2", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844, received_pallet:89545},
    {status:"test3", wms_doc:"wms_doc3", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844, received_pallet:89545},
    {status:"test4", wms_doc:"wms_doc4", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844, received_pallet:89545},
    {status:"test5", wms_doc:"wms_doc5", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844, received_pallet:89545},
    {status:"test1", wms_doc:"wms_doc1", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844, received_pallet:89545},
    {status:"test2", wms_doc:"wms_doc2", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844, received_pallet:89545},
    {status:"test3", wms_doc:"wms_doc3", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844, received_pallet:89545},
    {status:"test4", wms_doc:"wms_doc4", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844, received_pallet:89545},
    {status:"test5", wms_doc:"wms_doc5", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844, received_pallet:89545},
    {status:"test1", wms_doc:"wms_doc1", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844, received_pallet:89545},
    {status:"test2", wms_doc:"wms_doc2", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844, received_pallet:89545},
    {status:"test3", wms_doc:"wms_doc3", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844, received_pallet:89545},
    {status:"test4", wms_doc:"wms_doc4", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844, received_pallet:89545},
    {status:"test5", wms_doc:"wms_doc5", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844, received_pallet:89545},
    {status:"test1", wms_doc:"wms_doc1", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844, received_pallet:89545},
    {status:"test2", wms_doc:"wms_doc2", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844, received_pallet:89545},
    {status:"test3", wms_doc:"wms_doc3", customer:"customer", grade:"grade", lot:"Lot", no_pallet:"no_pallet", qty:3500.254, unit:"Unit", waiting_pallet:6844, received_pallet:89545},
  ];

  export default {monitorReceive}